In [1]:
!pip install datasets pandas pymongo sentence_transformers
!pip install -U transformers accelerate

Collecting datasets
  Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Collecting pymongo
  Downloading pymongo-4.11.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.11/dist-packages (3.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.13)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Downloading dnspython-2.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (4.48.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (2.5.1+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (1.13.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (11.1.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence_transformers)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence_transformers)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence_transformers)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence_transformers)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence_transformers)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence_transformers)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence_transformers)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence_transformers)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence_transformers)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence_transformers)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.5.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence_transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence_transformers) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.2)
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 17.1 MB/s eta 0:00:00
Downloading pymongo-4.11.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 36.2 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.7 MB/s eta 0:00:00
Downloading dnspython-2.7.0-py3-none-any.whl (313 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.6/313.6 kB 16.8 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 9.1 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.8 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 60.5 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 45.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 39.5 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.7 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.6 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 6.6 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.9 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 49.0 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 12.3 MB/s eta 0:00:00
Installing collected packages: xxhash, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, dnspython, dill, pymongo, nvidia-cusparse-cu12, nvidia-cudnn-cu12, multiprocess, nvidia-cusolver-cu12, datasets
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed datasets-3.3.2 dill-0.3.8 dnspython-2.7.0 multiprocess-0.70.16 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 pymongo-4.11.2 xxhash-3.5.0
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.48.3)
Collecting transformers
  Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: accelerate in /usr/local/lib/python3.11/dist-packages (1.3.0)
Collecting accelerate
  Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.28.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (2.5.1+cu124)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.3.1.170)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 74.1 MB/s eta 0:00:00
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 22.1 MB/s eta 0:00:00
Installing collected packages: transformers, accelerate
  Attempting uninstall: transformers
    Found existing installation: transformers 4.48.3
    Uninstalling transformers-4.48.3:
      Successfully uninstalled transformers-4.48.3
  Attempting uninstall: accelerate
    Found existing installation: accelerate 1.3.0
    Uninstalling accelerate-1.3.0:
      Successfully uninstalled accelerate-1.3.0
Successfully installed accelerate-1.4.0 transformers-4.49.0

In [2]:
from datasets import load_dataset
import pandas as pd

In [3]:
dataset=load_dataset("MongoDB/embedded_movies")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

README.md:   0%|          | 0.00/6.17k [00:00<?, ?B/s]

sample_mflix.embedded_movies.json:   0%|          | 0.00/42.3M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1500 [00:00<?, ? examples/s]

In [4]:
dataset_df=pd.DataFrame(dataset["train"])
dataset_df.head()

,plot,runtime,genres,fullplot,directors,writers,countries,poster,languages,cast,title,num_mflix_comments,rated,imdb,awards,type,metacritic,plot_embedding
0,Young Pauline is left a lot of money when her ...,199.0,[Action],Young Pauline is left a lot of money when her ...,"[Louis J. Gasnier, Donald MacKenzie]","[Charles W. Goddard (screenplay), Basil Dickey...",[USA],https://m.media-amazon.com/images/M/MV5BMzgxOD...,[English],"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",The Perils of Pauline,0,None,"{'id': 4465, 'rating': 7.6, 'votes': 744}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.0007293965299999999, -0.026834568000000003,..."
1,A penniless young man tries to save an heiress...,22.0,"[Comedy, Short, Action]",As a penniless man worries about how he will m...,"[Alfred J. Goulding, Hal Roach]",[H.M. Walker (titles)],[USA],https://m.media-amazon.com/images/M/MV5BNzE1OW...,[English],"[Harold Lloyd, Mildred Davis, 'Snub' Pollard, ...",From Hand to Mouth,0,TV-G,"{'id': 10146, 'rating': 7.0, 'votes': 639}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.022837115, -0.022941574000000003, 0.014937..."
2,"Michael ""Beau"" Geste leaves England in disgrac...",101.0,"[Action, Adventure, Drama]","Michael ""Beau"" Geste leaves England in disgrac...",[Herbert Brenon],"[Herbert Brenon (adaptation), John Russell (ad...",[USA],None,[English],"[Ronald Colman, Neil Hamilton, Ralph Forbes, A...",Beau Geste,0,None,"{'id': 16634, 'rating': 6.9, 'votes': 222}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.00023330492999999998, -0.028511643000000003..."
3,"Seeking revenge, an athletic young man joins t...",88.0,"[Adventure, Action]",A nobleman vows to avenge the death of his fat...,[Albert Parker],"[Douglas Fairbanks (story), Jack Cunningham (a...",[USA],https://m.media-amazon.com/images/M/MV5BMzU0ND...,None,"[Billie Dove, Tempe Pigott, Donald Crisp, Sam ...",The Black Pirate,1,None,"{'id': 16654, 'rating': 7.2, 'votes': 1146}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[-0.005927917, -0.033394486, 0.0015323418, -0...."
4,An irresponsible young millionaire changes his...,58.0,"[Action, Comedy, Romance]","The Uptown Boy, J. Harold Manners (Lloyd) is a...",[Sam Taylor],"[Ted Wilde (story), John Grey (story), Clyde B...",[USA],https://m.media-amazon.com/images/M/MV5BMTcxMT...,[English],"[Harold Lloyd, Jobyna Ralston, Noah Young, Jim...",For Heaven's Sake,0,PASSED,"{'id': 16895, 'rating': 7.6, 'votes': 918}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.0059373598, -0.026604708, -0.0070914757000..."

In [5]:
dataset_df.columns

Index(['plot', 'runtime', 'genres', 'fullplot', 'directors', 'writers',
       'countries', 'poster', 'languages', 'cast', 'title',
       'num_mflix_comments', 'rated', 'imdb', 'awards', 'type', 'metacritic',
       'plot_embedding'],
      dtype='object')

In [6]:
dataset_df.isnull().sum()

plot                   27
runtime                15
genres                  0
fullplot               48
directors              13
writers                13
countries               0
poster                 89
languages               1
cast                    1
title                   0
num_mflix_comments      0
rated                 308
imdb                    0
awards                  0
type                    0
metacritic            928
plot_embedding         28
dtype: int64

In [7]:
dataset_df=dataset_df.dropna(subset=["fullplot"])

In [8]:
dataset_df["fullplot"].isnull().sum()

0

In [9]:
dataset_df = dataset_df.drop(columns=["plot_embedding"])

In [10]:
dataset_df.head(2)

,plot,runtime,genres,fullplot,directors,writers,countries,poster,languages,cast,title,num_mflix_comments,rated,imdb,awards,type,metacritic
0,Young Pauline is left a lot of money when her ...,199.0,[Action],Young Pauline is left a lot of money when her ...,"[Louis J. Gasnier, Donald MacKenzie]","[Charles W. Goddard (screenplay), Basil Dickey...",[USA],https://m.media-amazon.com/images/M/MV5BMzgxOD...,[English],"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",The Perils of Pauline,0,None,"{'id': 4465, 'rating': 7.6, 'votes': 744}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN
1,A penniless young man tries to save an heiress...,22.0,"[Comedy, Short, Action]",As a penniless man worries about how he will m...,"[Alfred J. Goulding, Hal Roach]",[H.M. Walker (titles)],[USA],https://m.media-amazon.com/images/M/MV5BNzE1OW...,[English],"[Harold Lloyd, Mildred Davis, 'Snub' Pollard, ...",From Hand to Mouth,0,TV-G,"{'id': 10146, 'rating': 7.0, 'votes': 639}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN

In [11]:
!pip install langchain_community langchain_openai

Collecting langchain_community
  Downloading langchain_community-0.3.19-py3-none-any.whl.metadata (2.4 kB)
Collecting langchain_openai
  Downloading langchain_openai-0.3.8-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.41 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (0.3.41)
Requirement already satisfied: langchain<1.0.0,>=0.3.20 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (0.3.20)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (2.0.38)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (2.32.3)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (6.0.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (3.11.13)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (9.0.0)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain_community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.4.0 (from langchain_community)
  Downloading pydantic_settings-2.8.1-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: langsmith<0.4,>=0.1.125 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (0.3.11)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain_community)
  Downloading httpx_sse-0.4.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: numpy<3,>=1.26.2 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (1.26.4)
Collecting langchain-core<1.0.0,>=0.3.41 (from langchain_community)
  Downloading langchain_core-0.3.43-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: openai<2.0.0,>=1.58.1 in /usr/local/lib/python3.11/dist-packages (from langchain_openai) (1.61.1)
Collecting tiktoken<1,>=0.7 (from langchain_openai)
  Downloading tiktoken-0.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.18.3)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.6 in /usr/local/lib/python3.11/dist-packages (from langchain<1.0.0,>=0.3.20->langchain_community) (0.3.6)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.11/dist-packages (from langchain<1.0.0,>=0.3.20->langchain_community) (2.10.6)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.41->langchain_community) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.41->langchain_community) (24.2)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.41->langchain_community) (4.12.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain_community) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain_community) (3.10.15)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain_community) (0.23.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai<2.0.0,>=1.58.1->langchain_openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai<2.0.0,>=1.58.1->langchain_openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai<2.0.0,>=1.58.1->langchain_openai) (0.8.2)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai<2.0.0,>=1.58.1->langchain_openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai<2.0.0,>=1.58.1->langchain_openai) (4.67.1)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.4.0->langchain_community)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain_community) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain_community) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain_community) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain_community) (2025.1.31)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy<3,>=1.4->langchain_community) (3.1.1)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.11/dist-packages (from tiktoken<1,>=0.7->langchain_openai) (2024.11.6)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain_community) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain_community) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.41->langchain_community) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<1.0.0,>=0.3.20->langchain_community) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<1.0.0,>=0.3.20->langchain_community) (2.27.2)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Downloading langchain_community-0.3.19-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 67.9 MB/s eta 0:00:00
Downloading langchain_openai-0.3.8-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.4/55.4 kB 4.6 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading httpx_sse-0.4.0-py3-none-any.whl (7.8 kB)
Downloading langchain_core-0.3.43-py3-none-any.whl (415 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 415.4/415.4 kB 26.7 MB/s eta 0:00:00
Downloading pydantic_settings-2.8.1-py3-none-any.whl (30 kB)
Downloading tiktoken-0.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 50.8 MB/s eta 0:00:00
Downloading marshmallow-3.26.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 3.7 MB/s eta 0:00:00
Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Installing collected packages: python-dotenv, mypy-extensions, marshmallow, httpx-sse, typing-inspect, tiktoken, pydantic-settings, dataclasses-json, langchain-core, langchain_openai, langchain_community
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 0.3.41
    Uninstalling langchain-core-0.3.41:
      Successfully uninstalled langchain-core-0.3.41
Successfully installed dataclasses-json-0.6.7 httpx-sse-0.4.0 langchain-core-0.3.43 langchain_community-0.3.19 langchain_openai-0.3.8 marshmallow-3.26.1 mypy-extensions-1.0.0 pydantic-settings-2.8.1 python-dotenv-1.0.1 tiktoken-0.9.0 typing-inspect-0.9.0

In [51]:
import os
import requests
from google.colab import userdata
from IPython.display import display, Markdown

In [45]:
from langchain_community.embeddings import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_openai import ChatOpenAI
from langchain_text_splitters import CharacterTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain.schema.runnable import RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

In [15]:
OPENAI_API_TOKEN=userdata.get('OPENAI_API_KEY')
os.environ["OPENAI_API_KEY"] = OPENAI_API_TOKEN

In [16]:
embeddings = OpenAIEmbeddings()

<ipython-input-16-73ad2f8e367a>:1: LangChainDeprecationWarning: The class `OpenAIEmbeddings` was deprecated in LangChain 0.0.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-openai package and should be used instead. To use it run `pip install -U :class:`~langchain-openai` and import as `from :class:`~langchain_openai import OpenAIEmbeddings``.
  embeddings = OpenAIEmbeddings()

In [18]:
def get_embedding(text):
  return embeddings.embed_query(text)
dataset_df["embedding"]=dataset_df["fullplot"].apply(get_embedding)

In [19]:
dataset_df.head(3)

,plot,runtime,genres,fullplot,directors,writers,countries,poster,languages,cast,title,num_mflix_comments,rated,imdb,awards,type,metacritic,embedding
0,Young Pauline is left a lot of money when her ...,199.0,[Action],Young Pauline is left a lot of money when her ...,"[Louis J. Gasnier, Donald MacKenzie]","[Charles W. Goddard (screenplay), Basil Dickey...",[USA],https://m.media-amazon.com/images/M/MV5BMzgxOD...,[English],"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",The Perils of Pauline,0,None,"{'id': 4465, 'rating': 7.6, 'votes': 744}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.0013864070074729867, -0.021930136729511107,..."
1,A penniless young man tries to save an heiress...,22.0,"[Comedy, Short, Action]",As a penniless man worries about how he will m...,"[Alfred J. Goulding, Hal Roach]",[H.M. Walker (titles)],[USA],https://m.media-amazon.com/images/M/MV5BNzE1OW...,[English],"[Harold Lloyd, Mildred Davis, 'Snub' Pollard, ...",From Hand to Mouth,0,TV-G,"{'id': 10146, 'rating': 7.0, 'votes': 639}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[4.691182729746811e-05, -0.016464981466321513,..."
2,"Michael ""Beau"" Geste leaves England in disgrac...",101.0,"[Action, Adventure, Drama]","Michael ""Beau"" Geste leaves England in disgrac...",[Herbert Brenon],"[Herbert Brenon (adaptation), John Russell (ad...",[USA],None,[English],"[Ronald Colman, Neil Hamilton, Ralph Forbes, A...",Beau Geste,0,None,"{'id': 16634, 'rating': 6.9, 'votes': 222}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[-0.001603801064735868, -0.0253569041225378, 0..."

In [20]:
!pip install "pymongo[srv]"==3.11

Collecting pymongo==3.11 (from pymongo[srv]==3.11)
  Downloading pymongo-3.11.0.tar.gz (771 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 771.7/771.7 kB 27.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting dnspython<2.0.0,>=1.16.0 (from pymongo[srv]==3.11)
  Downloading dnspython-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 kB 16.0 MB/s eta 0:00:00
Building wheels for collected packages: pymongo
  Building wheel for pymongo (setup.py) ... done
  Created wheel for pymongo: filename=pymongo-3.11.0-cp311-cp311-linux_x86_64.whl size=495611 sha256=49286568bc11a29beb2e9fea7d31902f276b42575924f6d7df1956a34561e207
  Stored in directory: /root/.cache/pip/wheels/43/00/27/6d27c275881078538e7cd04e595f2f3a1f14b1ef9e32e40583
Successfully built pymongo
Installing collected packages: pymongo, dnspython
  Attempting uninstall: pymongo
    Found existing installation: pymongo 4.11.2
    Uninstalling pymongo-4.11.2:
      Successfully uninstalled pymongo-4.11.2
  Attempting uninstall: dnspython
    Found existing installation: dnspython 2.7.0
    Uninstalling dnspython-2.7.0:
      Successfully uninstalled dnspython-2.7.0
Successfully installed dnspython-1.16.0 pymongo-3.11.0

In [24]:
!python --version

Python 3.11.11

In [25]:
from pymongo.mongo_client import MongoClient

uri = "mongodb+srv://SolidSnake:abcd@cluster0.wnyre.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri)

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [27]:
db = client["mongorag"]
collection = db["mongoragcollection"]

In [28]:
collection.insert_one({
    "name": "sunny",
    "age": 25,
    "city": "Delhi"
})

In [29]:
document = dataset_df.to_dict("records")
collection.insert_many(document)

In [31]:
len(dataset_df["embedding"][0])

1536

In [32]:
def vector_search(user_query,collection):

  query_embedding=get_embedding(user_query)
  print(query_embedding)

  if query_embedding is None:
    return "Invalid query or embeddig is failed"

  pipeline=[

            {
                "$vectorSearch":{

                "index": "vector_index",
                "queryVector": query_embedding,
                "path": "embedding",
                "numCandidates": 150,  # Number of candidate matches to consider
                "limit": 4,  # Return top 4 matches


                }

            },

              {
                 "$project":{

                "fullplot": 1,  # Include the plot field
                "title": 1,  # Include the title field
                "genres": 1,  # Include the genres field
                "score": {"$meta": "vectorSearchScore"},  # Include the search score
                 }

            }

           ]

  result=collection.aggregate(pipeline)
  return list(result)

In [34]:
vector_search("what is the best horror movie to watch and why?",collection)

[0.015917836713390806, -0.021245762119484143, -0.004948772321657798, -0.03537003908448195, -0.008980983476445914, -0.017579517452005408, -0.00953487643510236, -0.02278875137676913, -0.019715962253293206, -0.0052125312725372335, -0.00798529434491561, 0.016379415110260476, 0.01506062128718593, -0.017302570041354555, -0.01122952599483893, 0.015535386281181757, 0.03639869983110211, 0.004094853777565119, 0.009884357114866809, -0.010167897358419426, -0.011269089511507926, 0.0029557458503717505, 0.006343396295958137, -0.019478579290633978, -0.007892978851806202, 0.01302967950745633, 0.0014135817449374439, -0.022604120390550313, -0.0008967795249505152, -0.008948013724001313, 0.0069632292251651, 0.005281767659538632, -0.021680963596810973, -0.01686736856402772, -0.027299023942003953, 0.0024793317168278523, -0.023197575934553124, -0.021615024091921772, 0.005423538246976256, -0.004315751398340732, 0.0146913593147483, -0.009561252423322567, -0.019122504846645134, -0.031308157387668005, 0.0027299024407665268, -0.0055422292626445555, 9.04094722243568e-06, -0.01823891250089742, -0.00977225939776159, -0.004394879363001352, 0.028934327761075716, 0.012020801916154606, -0.012456004324804069, -0.03650420378398294, 0.021707340516353812, -0.004009132048680105, 0.014796862336306494, 0.001803450045483608, 0.035765679839107674, -0.01734213448934618, 0.014163841412989429, 0.005044384696879403, -0.027378150975341943, 0.036820711917334895, 0.004915802569213198, 0.020032472249290424, -0.011519660933938573, 0.012653822839471673, -0.012653822839471673, -0.019254383856423536, 0.03368198328896977, 0.020863312618597724, 0.006168656421737227, 0.010141521370199219, 0.009224960203329536, -0.03465789019650426, -0.013979210426770612, -0.009000765700441726, 0.002861781683375587, -0.010899827539070294, 0.02285469088165833, -0.004889426580992991, -0.01717069103157615, 0.0128582360496863, 0.018898309412434693, 0.010326152356418036, -0.017526765475564993, 0.015047432827414511, -0.00539056802887034, -0.010754760069520473, 0.01025361908730444, -0.021074318661714116, 0.01215268185725564, 0.014902366289187322, -0.013201122033903726, 0.006142280433517021, -0.009284305943994344, 0.02988385961171263, -0.02187878397412384, 0.011064677232615928, 0.004965257197880099, -0.014480352340309277, -0.0077017536357016775, -0.016854181035578935, 0.02154908458703257, -0.016234346709388024, 0.01438803684719987, -0.015917836713390806, 0.023197575934553124, 0.004872941704770691, 0.004533352602665464, 0.017882839919553837, 0.0011193259360282133, -0.05628610367952008, 0.011770231425046589, -0.022524991494567062, 0.013398941479893959, -0.00014815819466659292, -0.01483642585297549, -0.01718387856002494, 0.017909214976451412, 0.02336901939232315, 0.017988342009789403, -0.03518540996090839, 0.034921651941351585, 0.004849863064323997, -0.013108806540794318, -0.008380932305573447, -0.0048696448226584945, -0.02877607369439974, 0.060136981195862894, 0.003873955691128191, 0.020705056689276483, -0.002934315418150497, -0.016458542143598466, 0.04650065582198708, -0.024555934205619294, 0.0012767569463294306, -0.018845557435994278, -0.008011670333135816, 0.01967639780530158, 0.016326663133820064, -0.007213800181934432, -0.007853415335137207, -0.02057317767949808, 0.013596759994561563, 0.003847579935738642, 0.03721635267196062, -0.01583870968005282, 0.00862490903245707, 0.015166124308744125, -0.013583572466112775, 0.02480650469672731, 0.011598787967276562, 0.0003470075234151538, 0.0018875231004818656, 0.022274421003459048, -0.012271373338585254, -0.01587827226539918, -0.011216338466390143, -0.02111388310970574, 0.017909214976451412, 0.011018519020399908, -0.011453721429049372, 0.006518136635840361, 0.026402244067807452, 0.022630495447447888, 0.0023672342325532897, 0.0013154964753010338, 0.005624654109417372, 0.008934825264229894, 0.048083207664618426, -0.03020036960770985, 0.02292063038654753, -0.014045149931659813, 0.01582552215160403, 0.01990059323951202, 0.006158765309739321, 0.0008291914043822223, 0.008156737802685637, 0.01673548955424932, 0.005476289757755354, 0.0372427277288582, 0.00543013201120065, -0.019333512752406787, 0.009027140757339302, 0.00972610118554557, -0.03468426897869236, 0.01142075074528214, -0.013636324442553189, -0.02063911718438728, 0.010082175629534413, 0.005799393983638281, -0.007978700580691216, -0.6363969827540235, -0.002497465034106251, -0.0051531855318724265, 0.0018215834791773355, 0.02226123347501026, 0.019504954347531554, 0.0195181437386256, 0.004724577353108673, 0.004474006862000657, 0.017909214976451412, 0.01641897769560684, 0.006003807193852909, 0.0264154334589015, -0.04402132596780448, -0.02377784581275241, -0.02371190630786321, 0.00534111340020344, -0.010128333841750431, -0.020876500147046513, 0.0037387793335762758, -0.037770243767971806, 0.041594746227417045, -0.04011769833766652, -0.012594477098806865, 0.03072788750946872, 0.01899062583686673, 0.012449409629257046, -0.023725093836311995, -0.013220904257899539, 0.016972872516908547, 0.007062138948160217, 0.030622383556587893, 0.005136700655650126, -0.0017012435567916226, 0.033339096373429716, -0.014480352340309277, -0.009937108159984592, 0.01047781359019225, -0.006066449816629914, 0.029092583690396957, -0.032363189465895226, -0.009435967177768559, 0.014242969377650048, 0.0010064042312256014, -0.006204923056294025, 0.01672230016315527, 0.016999247573806123, 0.010800918281736493, 0.01627391115737965, 0.02534721012693497, -0.0016311826000161888, -0.0031964256951431767, -0.017988342009789403, 0.0003029103572844053, 0.016181594732947613, -0.007220393946158826, 0.03610856302935721, -0.018067470905772653, -0.0008271307366467704, 0.013273656234339952, -0.019386262866201938, 0.021298514095924554, -0.025558216170051364, -0.03270607638143528, -0.0052949556536487355, 0.038561521551932744, 0.004902614575103095, 0.001091301623167237, -0.0063565842900682405, -0.033128092192958584, 0.031070772562363513, 0.008156737802685637, -0.027879293820203238, -0.0279847959104388, 0.0032607167589762793, 0.028195803816200453, 0.027800164924219987, 0.006290644785179039, 0.014572667833418684, 0.016049715723169208, 0.008011670333135816, 0.0039794591783477015, -0.029013454794413706, 0.01922800879952596, 0.021311701624373344, 0.012818672533017307, 0.0037453733306313276, -0.0027249568847675736, 0.0061323893215191145, 0.0019122505312306449, -0.007576468390147669, -0.002645829385768269, -0.01909612978974756, 0.002291403615666182, 0.004849863064323997, 0.030094865654829023, -0.012515350065468877, 0.007279739686823633, -0.004009132048680105, -0.024516369757627672, -0.0010261861059754275, -0.03049050454680949, -0.02226123347501026, 0.007398431168153247, 0.016761864611146895, -0.0015240306717405792, 0.03436775712004988, 0.0017078375538466743, 0.021232574591035353, -0.03246869341877605, 0.006936853702606208, 0.010016236124645212, -0.017909214976451412, -0.020718244217725272, 0.014018773943439608, -0.026085734071810234, 0.011941674882816618, 0.018027906457781028, 0.026296741977571887, -0.013201122033903726, 0.014559479373647266, 8.850340040759948e-05, -0.011453721429049372, -0.021232574591035353, 0.03188842726586729, 0.018660926449775465, 0.008572157056016657, 0.005726860714524686, -0.04866347754281771, -0.02179965507814059, -0.0036200880850773194, 0.014928741346084897, -0.0003482438833110599, -0.006765410244836181, -0.014111089436549016, 0.0003016739973884992, 0.0065807792586173655, -0.01140096945260896, -0.010616287295517677, 0.0015759581948222856, -0.004892723463105189, -0.005970837441408309, 0.013689075487670972, 0.017619080037351773, -0.0209556271803845, -0.027378150975341943, -0.005562011486640367, 0.0011250957125552158, 0.005505962628087758, 0.008255647060019439, 0.003326656496696138, -0.016933308068916922, 0.006709361851944886, 0.0015347458878512059, -0.0127922965447971, -0.0077017536357016775, 0.015851897208501605, -0.0047047955947741756, -0.0020672086471170566, 0.0020705057620599115, 0.025676907651380976, 0.012350500371923243, -0.011928486423045198, 0.008117173354694012, 0.01188232914215181, -0.022366737427891085, 0.004035508036900312, 0.024120732728292463, 0.004991633186100306, -0.02377784581275241, -0.0015784308564064332, 0.009970078843751822, 0.004335533622336545, 0.0401440733945641, 0.00046528680716924695, 0.019333512752406787, 0.007503934655372758, -0.018740055345758715, -0.02156227211548136, 0.014322096410988038, 0.007721535394036174, 0.009554658659098172, 0.010517378038183875, 0.02801117282998164, 0.009488719154208972, 0.0097590718693128, 0.007800663358696795, -0.013121995000565736, -0.010662444576411067, 0.007721535394036174, 0.0326797013245377, 0.01916206929463676, -0.019280760775966372, 0.009468936930213159, -0.013715451475891177, -0.020678681632378907, 0.021839219526132214, 0.024872444201616512, 0.010016236124645212, 0.02996298664505062, 0.045366494847776606, -0.005258689019091938, -0.01573320572717199, -0.006145577315629218, -0.0044212548855602435, -0.013728639935662597, 0.0027266053258236723, -0.02011159928262841, 0.01558813825762217, 0.039458299563483984, 0.006910477714386002, -0.034262253167169056, -0.005476289757755354, -0.01194826864704101, 0.030622383556587893, 0.007945730828246615, 0.00416079328245432, 0.031070772562363513, -0.03753286080531258, 0.006577482376505168, -0.003216207453477674, -0.010392091861307236, 0.015574950729173382, -0.00038883799578227034, 0.002838702810098235, 0.0070885149363804235, 0.017935590033348988, -0.003603602976024361, 0.01506062128718593, -0.01213949339748422, -0.04109360524520101, 0.02801117282998164, -0.018423543487116237, 0.022313985451450673, 0.012330719079250062, -0.005456507999420856, 0.0006008752749851863, 0.008328180329133034, -0.006000510311740712, -0.005723563366751174, -0.014374848387428451, 0.03167741936010564, -0.004896020810878701, -0.006152171545514927, 0.01883236990754549, 0.02566372012293219, 0.010497595814188063, 0.007292927680933737, -0.01899062583686673, -0.020243480155052077, -0.02007203669728205, -0.0007966336457863176, 0.013675887959222184, 0.0037255915722968305, -0.016761864611146895, -0.02526808309359698, 0.008802946254451492, 0.012027396611701631, 0.014374848387428451, 0.013860518945440999, 0.00412122930012401, 0.005156482413984624, 0.01304946080012951, -0.024661438158500124, -0.018515859911548273, -0.00044262004415591966, -0.017605892508902984, -0.0046223712136626745, 0.017605892508902984, -0.009033735452886327, -0.020612742127489706, -0.0007636638351340526, 0.001063277193890932, 0.00884910353534488, 0.013187934505454937, 0.018581799416437474, 0.01688055609247651, 0.017896027448002626, -0.007358867185822938, -0.0009577737648790853, -0.00771494162981178, -0.035844805009800404, 0.023672341859871583, 0.007734723388146278, -0.010200867110864027, -0.013939646910101619, -0.028354059745521694, -0.02181284260658938, -0.012765920556576894, 0.026230802472682686, -0.020283042740398438, -0.008440278046238255, -0.002652423382823321, -0.0065807792586173655, -0.0077017536357016775, 0.023751470755854834, 0.015640889302739953, -0.011315247723723944, 0.013689075487670972, -0.00787319662781039, -0.004302563404230629, -0.006442306018953254, -0.01590464918494202, -0.03273245143833285, 0.011097646985060529, 0.006152171545514927, 0.011888922906376205, -0.014335284870759456, 0.010451437601972044, -0.003501396603747705, 0.0056609207439741694, -0.009013953228890514, -0.020612742127489706, -0.024780129639829736, 0.006089528922737923, -0.004467412632114947, -0.014730922831417293, -0.007695159871477284, 0.04230689511539473, 0.014493539868758065, -0.01627391115737965, 0.007655595889146973, 0.0056609207439741694, -0.011480096485946948, 0.11837489869045195, 0.01558813825762217, 0.0048465657165504845, 0.019320323361312737, -0.013187934505454937, -0.012845048521237513, -0.021773280021243013, -0.03120265343478718, 0.024002041246962848, 0.007813850887145582, 0.011361405935939964, -0.008090797366473806, 0.011222932230614538, 0.010734978776847292, 0.01033274705196506, -0.009857981126646603, -0.003966271184237599, 0.003867361694073139, -0.009304088167990155, -0.01140096945260896, -0.01731575756980334, 0.00514329441987452, 0.0449444790362533, 0.007134672682935128, -0.0176586444853434, -0.01908294039865351, 0.01135481124039294, -0.00707532694227032, -0.006465384659399948, -0.012231808890593629, -0.023092073844317558, -0.015917836713390806, -0.01143393920505356, 0.006673094751726773, -0.010108551617754619, 0.016313475605371275, -0.010207460875088422, 0.009238147731778324, 0.03631957093511886, -0.02127213903902698, 0.0039003316793483974, 0.01581233276050998, 0.00014702486233669299, -0.011546036922158779, 0.011763637660822196, 0.0015182608952135769, 0.015535386281181757, 0.02467462568694891, 0.0070291691957156165, 0.005370786270535843, 0.049059114572152916, 0.0029227758650964926, -0.017078374607144113, 0.013174746045683519, 0.0099964539006494, -0.008519406010898874, -0.03352372922229379, 0.024331738771408856, -0.025821976052253427, 0.01901700089376431, -0.015680453750731578, -0.038614271665727895, 0.012231808890593629, 0.012192245373924633, -0.008618315268232677, -0.03012124257437186, 0.011644946179492582, -0.02459549679096566, -0.000773142662244941, -0.004526758372779755, 0.019320323361312737, -0.03993306548880245, -0.011664728403488395, -0.013715451475891177, 0.020309419659941277, 0.004839971952326091, 0.01809384596267023, 0.00365305783752192, -0.009251336191549742, 0.010392091861307236, -0.017144314112033314, -0.012429628336583863, 0.008387526069797842, -0.0256505325944834, -0.0038508768178508387, -0.006791786233056388, -0.00136742399838274, -0.019043377813307144, -0.00023635251237617394, 0.01694649559736571, 0.015944213632933645, 0.033866616137833844, 0.01217246314992882, -0.016392602638709265, 0.014849614312746909, 0.018344416453778246, 0.017961966952891827, 0.011822983401487002, 0.01597058868983122, -0.01218565160970024, 0.012614259322802678, -0.01777733596667301, -0.014045149931659813, -0.000447977652211233, 0.025241706174054145, -0.016247536100482074, -0.015271628261624952, 0.01946539176218519, 0.015614514245842377, -0.020850125090148934, 0.04320367312694597, -0.013227498022123932, 0.003976162296235505, -0.002909588103817047, 0.02853869073174051, 0.025756036547364226, 0.0012536780730520787, 0.019320323361312737, -0.002457901284606599, -0.01777733596667301, -0.006798379997280782, -0.018041093986229818, 0.0177245839902326, 0.027668285914441582, -0.012587883334582472, -0.00041851086611467393, 0.008328180329133034, -0.02922446270017536, -0.0022023850046689717, 0.0009569494861433717, -0.04465434595979892, 0.02247223951812665, 0.014638607338307887, -0.009271117484222925, -0.03668883290755649, -0.012080147656819414, -0.007292927680933737, 0.023144825820757973, -0.0014045149698829157, -0.0037222944573539756, -0.01946539176218519, -0.0072599579284891354, -0.006758816480611787, -0.03658332895467566, -0.016669548186714858, -0.026217613081588636, -0.006115904445296814, -0.008275429284015251, 0.012469191853252857, -0.013583572466112775, -0.03911541264794393, -0.01335278326767794, -0.02521533111715657, 0.008948013724001313, 0.014638607338307887, -0.03842964254215434, -0.014730922831417293, 0.002029293338673503, 0.013807766969000585, 0.005416944017090547, 0.01937307533775315, 0.006765410244836181, 0.014045149931659813, 0.02877607369439974, -0.011031707480171328, 0.004206951029009024, -0.0011275683741393636, 0.00305465534053621, -0.025927478142488993, 0.03194117737966244, 0.011941674882816618, 0.002741441760989874, -0.00870403699711769, 0.00908648649800411, 0.016142032147601248, 0.029118958747294532, 0.032152185285424094, 0.0007273970259542617, -0.019359887809304362, -0.038957158581267956, 0.011875735377927417, 0.008499623786903061, -0.016023340666271632, 0.006765410244836181, 0.005918085464967896, -0.02187878397412384, 0.011743855436826383, 0.0005674932958612322, 0.011328435252172734, -0.029936611588153045, 0.025993419510023454, 0.004602588989666862, -0.004856456828548391, -0.02045448619816847, 0.020494050646160094, -0.015086997275406137, 0.007550092401927462, -0.010227243099084234, 0.000288280006354048, 0.0004619898377455533, 0.0324159433049809, 0.011816389637262609, -0.0015718369757667106, -0.007233581940268929, 0.0010072284517536505, 0.02143039310570296, 0.011664728403488395, 0.010279995075524647, -0.0015924430710445858, -0.015245252273404746, -0.02616486110514822, -0.03270607638143528, -0.0019847840331748976, -0.019030190284858355, 0.009739289645316989, 0.0014531454944370962, -0.018133410410661854, -0.0017375103077637492, -0.01822572497244863, 0.002098529958505559, 0.00452016460855536, -0.008967795016674494, 0.029118958747294532, 0.04154199238833137, 0.009666756376203393, 0.01370226394744239, -0.034895273159163485, -0.003933301431792997, -0.0009890951344752518, -0.01031955859219364, -0.0022716216245010274, -0.00817651909535882, -0.009844792666875183, 0.01031955859219364, -0.018885121883985903, -0.0006573361273864922, -0.013385753020122541, -0.0400121943847857, -0.03376111218495302, 0.004315751398340732, 0.011440532969277953, 0.016168407204498823, -0.007405025398038957, -0.005232313030871731, -0.00476743821755118, 0.005545526610418067, -0.026481372963790703, -0.0005114445537239508, 0.00475095334132888, -0.024318551242960066, -0.0070885149363804235, 0.00182652891876096, -0.02232717297989946, -0.007273145922599239, -0.020296230268847228, -0.029145335666837368, 0.005904897470857792, -0.013036273271680722, -0.016089280171160833, 0.0072533636986034265, -0.014625418878536467, 0.017447636579581743, -0.027641910857544007, -0.010082175629534413, 0.016775052139595684, -0.0019633538337843017, 0.016590421153376868, 0.017223443008016565, -0.013135182529014524, 0.027114392955785136, 0.0008176519095358819, 0.004289375875781841, 0.002995309599871403, 0.0003838925270948138, -0.026217613081588636, -0.033998495147612245, -0.010418467849527444, -0.001476224367714448, 0.01400558641499082, -0.00793913613269959, 0.0328115803343161, 0.021694152987905023, -0.004203654146896827, -0.009910733103087016, -0.026666003950009516, -0.008611721504008282, -0.01074816630529608, 0.01090642130329469, 0.011203150006618725, -0.017210253616922515, 0.0006832998307196809, 0.0015413398849062577, -0.004246515011339334, 0.01100533149195112, 0.019702774724844416, 0.013491256973003367, 0.004256405657675925, 0.039642932412348064, -0.022564555942558687, -0.007536904407817359, 0.005838957965968591, 0.009106268721999922, -0.03265332626764013, -0.006455494013063357, 0.015218876285184538, -0.016999247573806123, 0.02518895419761373, -0.010181085818190844, 0.0011382835902499903, -0.023289892358985164, -0.003471723733415301, 0.001347642007217585, 0.00730611567504384, -0.024424055195840892, 0.010708602788627085, 0.03927367043991043, 0.005031197168430615, -0.019847841263071608, 0.012508755369921852, 0.012337312843474455, -0.024635061238957284, 0.002884860556652939, 0.01771139646178381, -0.005172967290206924, 0.019650022748404005, -0.017012435102254912, 0.029092583690396957, -0.019122504846645134, 0.0015685399772391846, -0.008374338541349054, -0.010616287295517677, 0.005558714138866856, -0.014124277896320434, -0.021509520139040946, -0.003761858206853628, -0.003283795632253631, -0.006439009136841057, 0.017381697074692542, -0.006930259472720499, -0.017750959047130175, -0.0185554243595399, 0.0032343410035867303, -0.015403507271403355, -0.0013336299089947612, -0.010616287295517677, -0.008948013724001313, 0.005931273459077999, -0.03223131045611682, -0.019359887809304362, -0.010952579515510708, -0.010022829888869605, 0.04172662523719545, 0.009383215201328145, 0.011598787967276562, -0.021232574591035353, 0.02662643950201789, -0.0343413820631523, 0.0003634924287412863, -0.009983266372200612, 0.032442318361878476, 0.04359931015628118, -0.02127213903902698, 0.020348982245287642, 0.027905668877100814, -0.0008374338424933724, 0.016168407204498823, -0.0030480613434811584, 0.027800164924219987, 0.003221153009476627, 0.007517122649482862, -0.00021090391776918378, 0.023738281364760784, -0.028670569741518912, -0.00980522915020619, 0.03668883290755649, 0.024912008649608137, -0.00648516688339

[{'_id': ObjectId('67cfb85d1a4e308a8116f4b3'),
  'genres': ['Action', 'Horror', 'Thriller'],
  'fullplot': 'A double-bill of thrillers that recall both filmmakers\' favorite exploitation films. "Grindhouse" (a downtown movie theater in disrepair since its glory days as a movie palace known for "grinding out" non-stop double-bill programs of B-movies) is presented as one full-length feature comprised of two individual films helmed separately by each director. "Death Proof," is a rip-roaring slasher flick where the killer pursues his victims with a car rather than a knife, while "Planet Terror" shows us a view of the world in the midst of a zombie outbreak. The films are joined together by clever faux trailers that recall the \'50s exploitation drive-in classics.',
  'title': 'Grindhouse',
  'score': 0.898036003112793},
 {'_id': ObjectId('67cfb85d1a4e308a8116f3db'),
  'genres': ['Action', 'Horror', 'Sci-Fi'],
  'fullplot': 'Ana, a young beautiful nurse finishes her day-shift at the hospital to return home to her beloved husband, they make love and sleep together. The next day, after her husband is killed by her neighbor next door, he suddenly comes back to life. She discovers the chaos happening in her neighborhood and escapes from her home. Soon after coming to her senses in the woods, she encounters a cop and other survivors, they decide to find safety in a mall. Soon more survivors come, and they learn that if they want to stay alive, they should stick together as the world is overrun by an army of undead. Can they survive the horror in this horrific global chaos? When there is no more room in hell, the dead will walk the earth',
  'title': 'Dawn of the Dead',
  'score': 0.8971732258796692},
 {'_id': ObjectId('67cfb85d1a4e308a8116f3ca'),
  'genres': ['Action', 'Adventure', 'Comedy'],
  'fullplot': "It's a high-kicking battle on the dark side when an ace vampire slayer and his beautiful sidekicks wage the ultimate martial-arts showdown with one of the most dangerous of the undead.",
  'title': 'Vampire Effect',
  'score': 0.8937157392501831},
 {'_id': ObjectId('67cfb85d1a4e308a8116f1c1'),
  'genres': ['Action', 'Comedy', 'Drama'],
  'fullplot': "A would-be movie producer strives to convince a self-help guru to let him film his book. As the guru is only interested in money, the producer solicits the help of a shady businessman and the guru's own secretary, who wants to write movie scripts (a horror story about brain-scraping monsters).",
  'title': 'Search and Destroy',
  'score': 0.892559826374054}]

In [35]:
def get_search_result(query,collection):

  get_knowledge=vector_search(query,collection)

  search_result=""

  for result in get_knowledge:
        search_result += f"Title: {result.get('title', 'N/A')}, Plot: {result.get('fullplot', 'N/A')}\n"

  return search_result

In [36]:
query="what is the best comedy movie to watch and why?"

In [37]:
source_information=get_search_result(query,collection)

[0.026924560224705272, -0.030204843927063914, -0.004060989953196075, -0.040019450365434146, -0.01913060887481349, 0.00026242261819042995, 0.0036345532022746055, -0.013265463723510434, -0.03149071534700475, -0.0004895822224364216, -0.001997692167514127, 0.015325481158434802, 0.031858107181273555, 0.003650954723231876, -0.00926351868696702, -0.0013744384456738773, 0.03004739081599015, -0.00634406704868455, 0.0162439598127843, -0.022082864020671764, -0.014682545448464385, -0.0028948495896771935, -0.00814166154527637, -0.027239468309497843, 0.005156604754487343, 0.022240317131745523, 0.028079221339632986, -0.019314304791947894, -0.00637030892342267, -0.009676834034858167, 0.010503465661962988, 0.0033508087989249937, -0.03201556029234732, -0.024969513082700952, -0.010116392188809959, -0.007433120682799395, -0.017739769955920182, -0.012353545305014833, 0.020810113072438727, -0.022673315049843417, 0.003158912354142585, -0.011238248399178084, -0.014315153614195577, -0.025625568333056643, -0.0070132446333930855, 0.004592396065715069, 0.011002068732567441, -0.01697874348132192, -0.009289760561705138, -0.008856763574929769, 0.027554374531645366, 0.030362297038137677, -0.026858956003521235, -0.012779982055936303, 0.01480063621309223, -0.007702103856985842, -0.003473819507612632, -0.0009570224847127801, 0.029050184674781248, -0.008843642171899448, 0.004444783308422156, 0.012694694333222999, -0.01880258031831312, 0.039966964753312864, -0.008666507421941467, 0.010477222855902347, 0.006078363992425053, 0.004805614441175804, 0.008640264615880824, -0.0068426696536277405, 0.02870903564657308, 0.02062641901794937, 0.009047019727918073, 0.010785569773518494, 0.025848627527959488, -0.024300335497992417, -0.021597382353097633, 0.0038740139181347214, 0.0023125993209841744, 0.005688010401345075, 0.02073138651690185, -0.007124774230844508, -0.01600778014617366, 0.012018956512660566, 0.0013481962216898118, 0.014682545448464385, -0.004553032322285367, 0.027160741753960962, -0.007702103856985842, -0.0020386957370766732, -0.001959968948709161, -0.007977647267026187, 0.0389960014181646, 0.023421219190088834, -0.01735925578729853, 0.015456692394770445, -0.012438832096405613, 0.010241043189291702, -0.009283200325851238, -0.0001590937084580706, 0.012392908582783274, -0.015942174062344574, 0.004654721100294679, -0.013960883182957089, 0.029417576509050056, -0.02010157220996175, 0.003235998850715991, -0.007301909446463752, 0.012517558651942495, 0.003959301175186763, 0.01564038831190485, 0.022935737522514703, -0.006242378270675238, -0.0455040832107606, -0.013593492280010803, -0.018540157845641836, 0.020442723100814967, -0.0025783023772436714, -0.027029529586302795, -0.009434093201071102, 0.018841943596081562, 0.0062194160482028065, 0.02713449894790032, -0.040413083143118554, 0.03180562156915227, -0.012937435167010064, -0.028131705089109223, -0.017897223066993942, 0.004185640953677819, -0.01053626870387753, 0.04647504654590886, -0.005651927241503584, 0.015915931256283933, -0.0033311271600407737, -0.02657029072478931, 0.03086090104006465, -0.014643182170695945, 0.010923341245708037, -0.006032440013141452, -0.009132307450631377, 0.012406029054491072, 0.02655717025308151, -0.023145674383064703, -0.016322686368321182, -0.031044596957199057, 0.003851051928492921, 0.00927664008999734, 0.03204180123576291, 0.005960273693458471, 0.0023552429495101953, 0.02847285411731739, -0.009985180952474316, 0.01746422514889605, 0.012799663694820523, -0.017569194510493574, 0.0186844904850078, 0.006718019118807259, 0.016768804758126872, -0.02578302330677545, -0.03212052779129979, 0.006068523172982943, 0.026019202973386096, 0.004041308314311855, -0.010831493287140835, -0.003844491459808391, 0.024746453887798107, 0.014498849531329981, 0.0013350750514901214, -0.00079505851299757, -0.00462847922555656, 0.024182243802042046, 0.046212622210592524, -0.011684366788983774, 0.031411988791467865, -0.00808261662862371, 0.00968995543788849, 0.01183526059552616, -0.009781803396455692, 0.007734906898900383, -0.002704593203858259, 0.014026489266786171, 0.022122227298440204, 0.03513838902098715, 0.0015368124321299562, -0.00767586151658646, 0.01693938020355348, 0.017516710761017337, -0.027764313254840415, 0.0029374932182032144, 0.0003317186018567003, -0.012839026972588964, 0.008233509503843573, 0.0028276036797152664, -0.014853119962568469, -0.6348527915932949, -0.010109831952956061, 0.005353421608990807, -0.012032076984368364, 0.042250042314462596, 0.010057347272157298, 0.0036017503931906948, -0.0004473485504436118, -0.0034606983374129417, 0.0021387444561225106, 0.0012850508083825179, 0.007052607911161526, 0.03959957291904405, -0.016257082147137145, -0.021492412991500107, -0.023040706884112225, 0.02571741722294637, -0.015089300560501635, -0.008200707393251554, -0.002499575588876159, -0.022975100800283144, 0.04051805436736112, -0.021872925297476715, -0.008614022741142703, 0.03193683373681044, 0.021085657879462857, 0.007761149239299764, -0.02460212124843214, -0.011402262677428268, 0.009375048284418442, -0.004018346557500685, 0.035112148077571556, 0.01717555987016412, -0.0013293346122873289, 0.035873172689524765, -0.010746206495750053, -0.026950803030765916, 0.002834164381230427, -0.005688010401345075, 0.01742486187112761, -0.016624473981405954, -0.0052812552893078245, 0.0126881340973691, -0.004884340996712685, -0.021046294601694417, 0.014944967921135671, 0.016388292452150267, 0.012898071889241624, -0.002253554171500883, 0.016322686368321182, 0.016611351647053112, 0.003003098836371036, -0.008056374753885591, -0.001220265219696434, 0.015010574004964755, 0.0020829796573967993, 0.03246167868215301, -0.013698460710285803, 0.0018320379467157834, 0.019957239570595788, -0.004146277210248117, 0.03395748696264384, -0.017608557788262015, -0.021886045769184514, 0.0032802827710361176, 0.04337845876068462, 0.0027341156621845893, -0.01012951359184028, 0.022725798799319654, -0.03973078508670222, 0.0070591686126766865, 0.001661463199781069, -0.03306525018303246, -0.017162439398456325, 0.01717555987016412, 0.04196137703573067, -0.0017647921531691716, -0.0008007990104080201, -0.0018664809311784842, 0.018067796649775505, 0.012392908582783274, 0.008108859434684352, -0.006580247180956455, 0.0009890052643149534, 0.014564455615159065, 0.023250643744662226, -0.0102541636609995, 0.0007405238167021224, 0.009932696271675555, -0.003978982814070983, 0.004290609849614081, 0.01136946056683625, -0.008705870699709906, 0.0006958299980564427, -0.0005232051192097274, 0.017437982342835407, -0.02035087421092524, 0.003513182785381073, 0.009716197312626608, -0.025218813221019393, 0.007006683931877925, -0.030152360177587673, -0.0016590029949205415, 0.019602970070679824, 0.004444783308422156, -0.008758355380508669, 0.023932943663723606, 0.017044349565151003, 0.008069495225593389, 0.0013678778605740322, 0.013685339307255481, -0.009283200325851238, -0.01306208616749181, -0.019235578236411015, 0.006901715035941663, -0.031359503179346576, 0.00799732983723293, 0.02502199683217719, 0.021794198741939833, 0.0036837575323157867, 0.009906454396937435, -0.016676957730882194, -0.01864512720723936, -0.012045198387398684, 0.015063058685763516, 0.041174107755071764, 0.01649326181374779, 0.0135016443214436, -0.04455936081902793, -0.016663837259174395, -0.00889612685269821, 0.0373689809700156, 0.009965499313590096, -0.007715225260016162, -0.010555950342761751, 0.013869035224389887, 0.009053580895094495, -0.023867337579894524, -0.01060187385638409, -0.003952740939332864, -0.004989309892648947, -0.013606612751718601, 0.010851175857347578, 0.0028866488291985582, -0.02713449894790032, -0.022004137465134882, -0.018094039455836146, -0.0016327607709364761, -0.008495931976514859, 0.009978619785297894, 0.007846436030690544, -0.011500671803171892, -0.015325481158434802, 0.008456568698746418, 0.006160371131550145, -0.005648647123576634, 0.0031900751042630206, -0.021872925297476715, 0.010306648341798263, -0.014879362768629112, 0.01742486187112761, 0.010037665633273078, -0.007964526795318389, -0.0002888699077525875, 0.027396921420571606, -0.007078850251560907, -0.008607461573966281, 0.0178578597892255, 4.120855146713019e-05, -0.02891897250712308, -0.005045074691374658, 0.007498726300967216, 0.014774393407031588, 0.02548123569369068, -0.0009406210801708247, 0.033117735795153744, 0.009814606438370232, -0.010313209508974686, -0.005661768060945694, 0.003272082010557482, 0.002581582495170621, 0.023998547884907642, -0.02071826604519405, -0.00808261662862371, 0.011802457553611619, 0.0006392451116413363, 0.019983482376656432, -0.015955294534052374, -0.024680847803969022, 0.005569920102378491, 0.011664685150099554, 0.018946912957679085, -0.008614022741142703, -0.011382581038544047, -0.009650592160120049, -0.011769654511697078, 0.008751794213332246, 0.009539062562668626, 0.023158796717417548, 0.014748151532293469, 0.02952254587064758, -0.011585958594562672, -0.011290733079976845, -0.020167178293790836, 0.005766736956881955, -0.01770040667815174, 0.0024372500886352877, -0.007793951815553044, 0.013764066794114885, 0.03261913179322677, -0.00212234293516524, -0.01880258031831312, -0.017542951704432933, -0.007767709475153663, 0.024457788609066177, 0.022266559937806168, -0.023762368218297, 0.03282907051642182, -0.029312607147452534, -0.004530070565474197, -0.00294897432943943, 0.0042971705511292415, 0.005783138477839227, 0.008325357462410775, 0.0038871350883344117, 0.005943872172501199, 0.013436038237614517, -0.01352788619618172, -0.0076168165999338, -0.01893379248597129, -0.03461354407564458, 0.02729195205897408, -0.0008717351694530807, 0.01944551695960606, 0.008856763574929769, -0.023290007022430666, 0.00892236872743633, 0.0036017503931906948, 0.004687524142209221, -0.0002825143591270054, -0.008594341102258483, 0.017503588426664492, -0.00850905337954518, -0.023421219190088834, 0.01896003529203193, 0.002791520752704406, 0.016335808702674027, 0.014131458628383695, 0.0033327672190042483, 0.015141785241300398, -0.027685586699303533, 0.0012112444297360612, 0.011664685150099554, 0.008856763574929769, -0.008535296185605824, -0.009617789118205508, 0.006088204811867164, 0.005209088969624843, 0.01941927415354542, 0.028000492921451056, -0.0021354641053649304, 0.0070132446333930855, 0.014485729059622183, -0.007452802321683615, -0.02347370293956507, -0.004776091517188212, 0.00927664008999734, -0.015168027116038516, -0.007656179877702241, -0.007918602350373526, -0.0030145799476072512, -0.003470539156855052, 0.0021502253345280957, 0.004516949162443876, 0.017149318926748525, 0.020770749794670286, -0.01645389853597935, 0.0365817116893567, -0.005133642532014911, -0.01310144944526025, -0.0014195423954757411, -0.06119695713478673, 0.03041478265025896, 0.001394120200973413, -0.016296445424905586, 0.00024397103808073016, -0.030965868539017127, -0.03550578085525596, -0.012071440262136803, 0.02141368643596323, -0.028052978533572342, 0.010628115731122208, -0.019222457764703216, 0.015023695407995075, 0.007629937537302859, 0.03435111974032824, 0.023053827355820025, 0.01596841686840522, 0.03225173995895796, -0.0019845709973144365, 0.005573200220305441, -0.001997692167514127, -0.013790308668853005, -0.042669919760852694, 0.009506259520754085, 0.009945817674705875, -0.004477585884675435, -0.012707815736253321, 0.015509177075569206, -0.029679998981721342, 0.002402807220587902, -0.0047892129202185335, -0.02420848660810269, -0.024077276303089572, -0.0030408220551760017, -0.007872678836751187, -0.01953736398685074, -0.0028850087702350833, 0.021951651853013596, 0.0014457846194598067, -0.02409039677479737, -0.01779225370539642, -0.007584013558019258, -0.004428381787464884, 0.11997962081547546, 0.006993562994508865, 0.002591423314612731, 0.004585835364199908, -0.0033885320177299595, -0.014131458628383695, -0.012045198387398684, -0.035322083075476504, 0.02107253740775506, -0.0013711582113316123, 0.012228894304533089, -0.008679627893649264, 0.03482348279883962, 0.01098238709368322, 0.013685339307255481, 0.0018025153719741374, -0.00023310509447496176, -0.0029834171974868155, 0.013790308668853005, -0.013842793349651767, -0.016834410841955957, 0.010883977967939596, 0.043089793481952694, 0.012825905569558642, -0.011894305512178821, -0.012012395345484143, 0.010956144287622578, 0.014262669864719338, 0.003318005989841083, -0.008574659463374263, -0.034009972574765124, -0.012865268847327083, -0.021702351714695155, 0.010496904494786565, -0.0059963568532999615, 0.014538212809098422, 0.0025947036653703112, 0.018330220985091836, 0.05004399366435438, -0.011316975886037488, -0.0047465690588618815, -0.00034278955283290307, 0.006206295110833746, -0.012786542291790201, 0.023053827355820025, -0.014656303573726267, 0.00634406704868455, 0.042223801371047004, 0.0034869406778123228, -0.008148222712452793, 0.040386842199702955, 0.009047019727918073, 0.0007614356162242641, 0.014026489266786171, 0.04282737287192646, 0.0007524148844715491, -0.028052978533572342, 0.004999151177752318, -0.024431545803005536, -0.0003542705476538034, -0.021361200823841943, -0.018828823124373763, 0.038602368640480195, 0.0021256232859228202, -0.023657398856699475, -0.031831862512567866, 0.008581219699228163, -0.03172689501361539, 0.0059471527560894105, -0.002158426095006731, 0.00045841953052364336, -0.04030811564416607, -0.02367052119105232, -0.01058219221749987, 0.024746453887798107, -0.004936825677511447, 0.02508760291600627, 0.0023437620711046106, -0.03550578085525596, 0.01573223533914953, -0.00974900035454115, -0.02412976005256581, 0.012373226943899054, -0.029260121535331248, -0.02037711701698588, 0.0052353313100242235, 0.0016532625557177491, 0.002922731989040049, -0.017936586344762383, 0.0186976109567156, 0.024064153968736728, 0.017070592371211647, 0.0027603580025839704, -0.008154782948306693, 0.018986276235447526, 0.0186976109567156, 0.019668576154508906, 0.029391333702989415, 0.009460335075809222, -0.016755684286419076, 0.009584986076290965, -0.03009987456546639, -0.0032753623613150625, -0.0072363038282959305, 0.01151379227487969, -0.008371281907355638, -0.0064359150072517525, 0.02420848660810269, -0.006422793604221431, -0.02411663958085801, 0.04017690347650791, -0.020652659961364967, 0.006176772652507417, -0.00589794865887886, 0.02996866426045327, 0.03041478265025896, 0.004280769030171971, 0.029784968343318865, 0.0019550485389881063, -0.008331918629587197, 0.006704898181438199, -0.026701501029802427, 0.005461670622854018, 0.030834658234004008, -0.017582314982201374, -0.006101325749236223, -0.0014958089789827253, -0.03663419730147798, 0.004261087391287751, 0.017569194510493574, -0.007590574259534419, 0.03099211134507777, 0.01480063621309223, -0.010779009537664596, -0.03576820519057229, -0.02234528649334305, -0.0020157337474348727, 0.018841943596081562, -0.00890268708855211, -0.002711153672542789, -0.014735030129263147, 0.004195481773119929, 0.013258902556334011, -0.03516462996440275, -0.0023765648801885213, -0.0262028988905205, -0.014026489266786171, -0.018080918984128346, 0.013403235195699975, -0.006501520625419574, -0.03017860112100327, -0.010765888134634274, -0.03154320095912603, -0.00043012708731609016, 0.01829085584467835, -0.03925842575348093, 0.006580247180956455, -0.01184182083138006, 0.00010174002257596382, 0.014721908726232826, 0.02794800917197482, 0.0065704063615143445, 0.024287213163639573, 0.020705145573486253, -0.0020632977856819483, 0.003568947584106784, -0.005966834394973631, -0.012812784166528321, -0.005619124199589042, 0.03191058906810475, 0.002117422525444185, -0.008633704380026924, -0.00927664008999734, 0.01859264345776312, 0.0013924800255946228, 0.01913060887481349, 0.028866488757646844, -0.007800512517068204, -0.019183094486934775, -0.03306525018303246, 0.010838054454317257, -0.009375048284418442, -0.008994535047119312, 0.002758717710789865, 0.019025639513215967, -0.004703925663166492, 0.008679627893649264, 0.016099627173418337, 0.0024831740679188887, 0.00383793075829323, 0.03393124601922824, -0.001294891627824628, 0.01307520757052213, -0.0006999303200881027, 0.012779982055936303, -0.023080070161880666, -0.016545745563224027, -0.020678902767425608, -0.009598107479321287, 0.009899893229761012, 0.03159568284595722, 0.0278167988669617, -0.015692872061381088, 0.000807769610248734, 0.0035492659452225636, 0.026019202973386096, -0.007977647267026187, -0.008574659463374263, 0.0018992837402623949, -0.010241043189291702, -0.02367052119105232, -0.026924560224705272, -0.001861560521457429, -0.029338849953513175, 0.012110804471227768, 0.001956688597951581, 0.0014613659945200246, 0.006406392083264161, -0.011913987151063041, 0.008358160504325318, -0.015705994395733933, -0.017398619065066966, 0.03251416429427429, 0.03340640107388567, 0.016270202618844945, 0.004608797121011078, -0.035085903408865866, 0.0023060388522996448, -0.004949946614880506, -0.0025044959985972143, -0.008653386018911144, -0.003434455997013561, -0.0031179087845800385, 0.03041478265025896, -0.020587053877535882, -0.010300088105944363, -0.02120374771276818, -0.024300335497992417, -0.03151695629042034, 0.01108735552395822, -0.0007146916074589257, 0.01957672726461918, -0.014485729059622183, 0.0007901381032765149, 0.007393757405030955, 0.012543801458003136, -0.0006486759163425778, 0.005359981844844706, 0.0010054066688569088, -0.004933545093923236, -0.006514641562788633, 0.00018984637107806576, -0.008692749296679585, -0.02465460499790838, -0.02752813358822977, -0.02237152929940369, 0.01401336786375585, -0.020639539489657167, -0.012504438180234697, 0.014262669864719338, -0.019589849598972024, 0.003962581758774974, -0.019996604711009273, 0.003929778716860432, 0.011244809566354506, -0.006947639015225264, 0.012346984137838411, 0.0066130502228709965, -0.011421944316312488, 0.023119433439649107, -0.012097683068197446, -0.006068523172982943, 0.00338525189980301, 0.0010636316724431476, 0.0063965512638220505, -0.04148901770250938, -0.007032926272277306, -0.009532501395492204, 0.007793951815553044, 4.7974136661452545e-05, 0.03296028268407998, 0.02844661131125675, 0.009801485035339912, 0.0023470424218621907, -0.011290733079976845, 0.011900865748032721, -0.01738549859335917, -0.00027779895677638474, 0.0014269230100573238, -0.018815702652665967, 0.013698460710285803, 0.0011718810355523053, -0.003572227934864364, 0.01899939856980037, 0.010792130009372394, 0.011244809566354506, -0.003568947584106784, 0.02339497638402819, -0.014275790336427136, -0.003542705476538034, -0.010365693258450924, 0.011159521843641202, -0.026373474335947104, -0.005750335901585946, 0.009053580895094495, -0.022673315049843417, 0.03629305013591486, -0.010674040176067072, -0.0051467634693839704, -0.02039023748869368, -0.004930264975996287, -0.009644030992943626, -0.003185154461711335, -0.018264614901262754, 0.0019960521085506523, 0.035873172689524765, 0.005701131338714134, -0.028682792840512436, 0.0053632624284329165, 0.017083712842919443, -0.025231935555372238, 0.007269106404549211, 0.034639785019060176, 0.015443570991740123, 0.012852148375619285, 0.002758717710789865, 0.017070592371211647, -0.010490344258932667, 0.009552183034376424, 0.00763649823881802, -0.022804525354856536, 0.005786418595766176, 0.015522298478599528, -0.005113960893130691, -0.0012875110132430454, -0.011179203482525423, -0.00023515527004270618, 0.04293234037087893, -0.024287213163639573, 0.0017943147279108175, 4.9614275660456636e-05, 0.027370678614510962, -0.0012350264488595992, 0.010903659606823816, -0.014774393407031588, -0.023001343606343785, -0.006186613471949527, -0.0050155522330483275, -0.01953736398685074, -0.0040741113562263965, 0.00806293498973949, 0.0262028988905205, 0.0007692263037543731, -0.0011341578167473395, -0.02331624982849131, 0.0035099026674541233, -0.027449407032692892, -0.016427655729918705, -0.00972275847980303, 0.033983727906059434, 0.03002114800992951, -0.024064153968736728, -0.009945817674705875, 0.017634800594322656, 0.002725914901705954, 0.018395825206275872, -0.006353907868126661, 0.015076180088793837, 0.00012413820556928388, 0.010562510578615649, -0.00011429734974738769, 0.011218566760293864, -0.007131334932359669, -0.01178933615058129

In [38]:
source_information

"Title: The Last Man, Plot: Apocalyptic comedy finds a socially-challenged grad school student as one of the last two men on Earth with a beautiful woman. However, the other remaining man is his superior in every sense.\nTitle: Fight Back to School, Plot: (Cantonese with English subtitles) Classic, slapstick, all-out-ridiculous Hong Kong action-comedy delivered by the one-and-only Stephen Chow (Kung Fu Hustle, Shaolin Soccer), who plays a SWAT team leader going undercover at a high school to retrieve a stolen gun for his captain.\nTitle: High Heels and Low Lifes, Plot: Two best girlfriends living in London suddenly find themselves battling wits with seasoned criminals when they decide to blackmail the culprits of a bank heist in their neighborhood rather than reporting the crime to the police. Refusing to be played by this new competition and give up the demanded $2 million, the leaders of the gang of robbers (Kevin McNally and Michael Gambon) decide to start playing dirty tricks, threaten violence and counterfeit money in an effort to throw the two women (played by Minnie Driver and Mary McCormack) off course. When the blackmail and counter attacks hurt an innocent bystander, the kooky best friends must use their friendship to empower each other to lure the hardened criminals into a risky trap.\nTitle: Shanghai Express, Plot: Multi-genre flick (western, martial arts, comedy, adventure, etc.) with an all-star cast about a man who returns to his home town, buys everything in sight, and tries to improve its municipal (and his personal) profits by sabotaging a train so the passengers all have to stop in his town and spend lots o' money! Throw in various subplots involving some Japanese swordsmen, some bungling bankrobbers (one of whom is the head of security), and a gang of no-goods who try to mess up the town.\n"

In [39]:
combined_information = f"Query: {query}\nContinue to answer the query by using the Search Results:\n{source_information}."

print(combined_information)

Query: what is the best comedy movie to watch and why?
Continue to answer the query by using the Search Results:
Title: The Last Man, Plot: Apocalyptic comedy finds a socially-challenged grad school student as one of the last two men on Earth with a beautiful woman. However, the other remaining man is his superior in every sense.
Title: Fight Back to School, Plot: (Cantonese with English subtitles) Classic, slapstick, all-out-ridiculous Hong Kong action-comedy delivered by the one-and-only Stephen Chow (Kung Fu Hustle, Shaolin Soccer), who plays a SWAT team leader going undercover at a high school to retrieve a stolen gun for his captain.
Title: High Heels and Low Lifes, Plot: Two best girlfriends living in London suddenly find themselves battling wits with seasoned criminals when they decide to blackmail the culprits of a bank heist in their neighborhood rather than reporting the crime to the police. Refusing to be played by this new competition and give up the demanded $2 million, the leaders of the gang of robbers (Kevin McNally and Michael Gambon) decide to start playing dirty tricks, threaten violence and counterfeit money in an effort to throw the two women (played by Minnie Driver and Mary McCormack) off course. When the blackmail and counter attacks hurt an innocent bystander, the kooky best friends must use their friendship to empower each other to lure the hardened criminals into a risky trap.
Title: Shanghai Express, Plot: Multi-genre flick (western, martial arts, comedy, adventure, etc.) with an all-star cast about a man who returns to his home town, buys everything in sight, and tries to improve its municipal (and his personal) profits by sabotaging a train so the passengers all have to stop in his town and spend lots o' money! Throw in various subplots involving some Japanese swordsmen, some bungling bankrobbers (one of whom is the head of security), and a gang of no-goods who try to mess up the town.
.

In [40]:
template = """
Query: {query}
Continue to answer the query by using the Search Results:
{source_information}
"""

In [43]:
prompt = ChatPromptTemplate.from_template(template)

In [46]:
model = ChatOpenAI(model="gpt-4o-mini")

In [48]:
rag_chain = (
    RunnablePassthrough()
    | RunnableLambda(lambda x: {"query": x, "source_information": source_information})
    | prompt
    | model
    | StrOutputParser()
)

In [49]:
result = rag_chain.invoke(query)

In [52]:
display(Markdown(result))

If you're looking for the best comedy movie to watch, "Fight Back to School" might take the top spot. This film is a classic in the realm of Hong Kong action-comedy, featuring the comedic genius of Stephen Chow, known for his iconic films such as "Kung Fu Hustle" and "Shaolin Soccer."

The plot centers around Chow's character, a SWAT team leader who hilariously goes undercover at a high school to retrieve a stolen gun. The film is packed with slapstick humor and outrageous scenarios, making it not only entertaining but also a nostalgic throwback for fans of the genre. The blend of action and comedy, combined with Chow's unique style of humor, provides a delightful viewing experience that is sure to elicit laughter.

While other films like "The Last Man" and "High Heels and Low Lifes" have their own charm, "Fight Back to School" stands out for its engaging plot, memorable comedic moments, and Stephen Chow's unforgettable performances. If you're in the mood for a lighthearted romp filled with laughter, this film is definitely a strong choice!